services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  loan:
    build:
      context: .
      dockerfile: services/loan/Dockerfile
    ports:
      - "8000:8000"
    environment:
    - AMQP_URL=amqp://guest:guest@rabbitmq:5672/%2F

    depends_on:
      - rabbitmq

  credit:
    build:
      context: .
      dockerfile: services/credit/Dockerfile
    ports:
      - "8001:8000"
    environment:
     - AMQP_URL=amqp://guest:guest@rabbitmq:5672/%2F

    depends_on:
      - rabbitmq

  property:
    build:
      context: .
      dockerfile: services/property/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/%2F
    depends_on:
      - rabbitmq

  decision:
    build:
      context: .
      dockerfile: services/decision/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/%2F
    depends_on:
      - rabbitmq

  notification:
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    ports:
      - "8004:8000"
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/%2F
    depends_on:
      - rabbitmq
